[functions]
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"Î